# Azure DevOps Pipeline for Node.js
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
  osList: [ 'ubuntu', 'macos', 'windows' ]
  nodeList: [ '8', '10', '12' ]

strategy:
  matrix:
    ${{ each os in parameters.osList }}:
      ${{ each nv in parameters.nodeList }}:
        ${{ format('{0}_node_{1}', os, nv) }}:
          imageName: ${{ format('{0}-latest', os) }}
          node_version: ${{ format('{0}.x', nv) }}

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  displayName: 'Install Node.js'


- script: 'npm install --no-package-lock && npm run ci'
  displayName: 'npm install and run ci'
