name: New Rule
description: Suggest a new rule for Markdownlint.
title: "[New rule]: "
labels: ["new rule"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new rule!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
