name: Checkers

on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

jobs:

  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - run: 'npx linkinator "*.md" "doc/*.md" "helpers/*.md" --directory-listing --skip "^https://github.com/.*/search\?q=" --skip "^https://www.jwz.org/" --skip "^https://wikipedia.org/"'

  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: tbroadley/spellchecker-cli-action@v1
      with:
        dictionaries: '.github/dictionary.txt'
        files: '*.md doc/*.md helpers/*.md'
